// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LocaleLayout": {
    "title": "next-intl example"
  },
  "common": {
    "login": "로그인",
    "lightmode": "라이트 모드",
    "darkmode": "다크 모드"
  },
  "kanuProfile": {
    "info": {
      "name": "박 한음",
      "address": "대한민국 광주광역시. qkrgksdma17@gmail.com",
      "job": "웹 풀 스택 엔지니어",
      "dob": "생년월일 : 1994. 09. 29"
    },
    "desc": {
      "0": { "text": "안녕하세요, " },
      "1": { "focus": "박한음" },
      "2": { "text": "입니다. 한국에서 " },
      "3": { "focus": "웹 풀 스택 개발자" },
      "4": { "text": "로 활동하고 있으며, " },
      "5": { "focus": "6년 차" },
      "6": { "text": "입니다. 주로 " },
      "7": { "focus": "NodeJS를 기반으로 개발하며 메인 언어는 Typescript" },
      "8": {
        "text": "입니다. 항상 새로운 영역을 개발하고, 기본을 충실하는 것을 선호합니다. 저에 관한 이력은 아래에 자세히 확인하실 수 있습니다!"
      }
    }
  },
  "kanuRecord": {
    "educations": {
      "title": "학력",
      "list": {
        "0": {
          "desc": "조선대학교, 컴퓨터 통계학과",
          "memo": "2013.03 ~ 2019.02 / 대한민국, 광주광역시 / 3.4(4.5)"
        },
        "1": {
          "desc": "세종고등학교, 이과계열",
          "memo": "2010.03 ~ 2013.02 / 대한민국, 광주광역시"
        }
      }
    },
    "careers": {
      "title": "경력",
      "list": {
        "0": {
          "desc": "(주)카라멜라, 웹 프론트 총괄 및 프로젝트 리드",
          "memo": "2019.10 ~ 2023.03(3년 6개월) / 대한민국, 광주광역시 / 개발팀, 책임연구원, 과장"
        }
      }
    },
    "contacts": {
      "title": "연락처",
      "list": {
        "0": {
          "desc": "이메일",
          "memo": "qkrgksdma17@gmail.com"
        },
        "1": {
          "desc": "이메일",
          "memo": "qksdbf15@naver.com"
        },
        "2": {
          "desc": "개인번호",
          "memo": "010-2397-8172",
          "masking": "true"
        }
      }
    },
    "project_desc": {
      "title": "프로젝트 이력",
      "list": {
        "0": {
          "desc": "프로젝트명 : 디지털 성범죄 검출 솔루션(METU)",
          "memo": "기간 : 2019.10 ~ 2020.01(4개월)",
          "extra": {
            "0": "개발 상세 내용 또는 참여 내용",
            "1": "- 프로토 타입 버전 Front-End 개발",
            "2": "- Languages : Javascript",
            "3": "- Frameworks : React.js, Express.js"
          },
          "path": "/project/metu"
        }
      }
    },
    "career_desc": {
      "title": "경력 기술서",
      "list": {}
    },
    "languages": {
      "title": "구사언어",
      "list": {
        "0": {
          "desc": "한국어",
          "memo": "모국어"
        },
        "1": {
          "desc": "영어",
          "memo": "기초(토익 650)"
        }
      }
    },
    "skills": {
      "title": "보유 기술",
      "list": {}
    },
    "documents": {
      "title": "포트폴리오/기타문서",
      "list": {
        "0": {
          "desc": "데이오프",
          "memo": "https://day-off.xyz",
          "route": "https://day-off.xyz"
        },
        "1": {
          "desc": "Github 주소",
          "memo": "https://github.com/haneum-park",
          "route": "https://github.com/haneum-park"
        }
      }
    },
    "licenseNawards": {
      "title": "자격증/수상내역",
      "list": {
        "0": {
          "desc": "자격증 / 정보처리기사 / 최종합격",
          "memo": "2019.08 / 한국산업인력공단"
        },
        "1": {
          "desc": "자격증 / 1종 보통 운전면허 / 최종합격",
          "memo": "2013.08 / 경찰청(운전면허시험관리단)"
        },
        "2": {
          "desc": "수상내역 / 아이디어상",
          "memo": "2019.02 / (사)스마트미디어인재개발원"
        },
        "3": {
          "desc": "수상내역 / 핵심 Web융합 프로젝트 최우수상",
          "memo": "2019.01 / (사)스마트미디어인재개발원"
        },
        "4": {
          "desc": "수상내역 / BASE창의 인재양성 Festival 콘텐츠상",
          "memo": "2018.12 / 과학문화교육사업단"
        },
        "5": {
          "desc": "수상내역 / 소트프웨어 경진대회 대상",
          "memo": "2019.06 / 조선대학교 자연과학대학"
        }
      }
    },
    "activities": {
      "title": "활동",
      "list": {
        "0": {
          "desc": "교육이수 / 빅데이터분석 전문가 과정 이수",
          "memo": "2018.09.03 ~ 2019.02.28 / (사)스마트미디어인재개발원"
        },
        "1": {
          "desc": "아르바이트 / 한울공사",
          "memo": "2016.07 ~ 2016.08 / 대한민국, 광주광역시"
        }
      }
    },
    "etc": {
      "title": "기타 사항",
      "list": {
        "0": {
          "desc": "대한민국 군필 / 육군 병장 만기전역",
          "memo": "2014.10 ~ 2016.07 / 대한민국, 파주시 문산읍"
        }
      }
    }
  }
};
export default messages;